# Generated by Django 3.1.3 on 2021-03-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraction',
            name='client',
            field=models.CharField(max_length=16, verbose_name='客户端'),
        ),
    ]
